pentaho/marketplace-metadata

marketplace.xml
AAAR v2.3 release.
AAAR v2.2 still remain valid but the default one is the latest (v2.3).
=> AAAR v2.3 release

marketplace.xml
* Fix a problem with JPivot migration.
* Fix formatting issue when aggregating on default measure.
* Fix CDE integration problem (blank page).
* Remove an error message on saving report (plugin)
* Update Russian translation.
=> Update Pivot4J to build #379

marketplace.xml
AAAR v2.4 cannot work with Pentaho 5.3
=> AAAR v2.4 cannot work with Pentaho 5.3

marketplace.xml
Version managment for pash. Includes a special version 0.14 / MONDRIAN-2263 to work around a particular XML/A problem in 5.3
=> Added versions for pash.

marketplace.xml
Dear Pentaho,
Please accept our update to the DataCleaner PDI plugin. Now based on version 4.0 of DataCleaner - we're very happy to launch this major new version into your community too :-)
Any comments welcome.
- Kasper, Dennis, Claudia and Tomasz from the DataCleaner team
=> Updated the DataCleaner plugin version to 4.0 (and new download URL)

marketplace.xml
Renamed license from "GLPL" to "LGPL"
=> Fix License Typo for Marketplace Plugin

marketplace.xml
Per the Development Stages standard in the Marketplace, Professionally
Supported plugins are assigned a Pentaho PM and are part of the Pentaho
release cycle
=> Update 3rd-party support level to Community

marketplace.xml
resolve the error: Invalid content was found starting with element 'screenshots'. One of '{market_entry}' is expected.
=> resolve the error for Add sequoiadb-screenshots

marketplace.xml
This is an alternate version of the "JSON Input" step that uses [Jayway JsonPath](https://github.com/jayway/JsonPath) instead of a parser based on JavaScript. It is intended to be a drop-in replacement for the "JSON Input" step but should be much faster and memory efficient.
The project can be explored at https://github.com/graphiq-data/pdi-fastjsoninput-plugin
* [[PDI-10344](http://jira.pentaho.com/browse/PDI-10344)] Replaced JavaScript parsing engine with Jayway JsonPath
* [[PDI-10858](http://jira.pentaho.com/browse/PDI-10858)] Checkbox to "Remove source field from output stream"
* Checkbox to enable JsonPath's `DEFAULT_PATH_LEAF_TO_NULL` [option](https://github.com/jayway/JsonPath#options) which returns `null` for missing leafs:
```python
[
{
"name": "Jesse Adametz",
"gender": "male" …
```
=> Add: PDI FastJsonInput Plugin

marketplace.xml
Version `1.0.2` contains a fix for the "Json files" filter that @mattyb149 mentions in #370.
=> Update: PDI FastJsonInput Plugin

marketplace.xml
This job entry allows you to send messages to Slack channels or groups.
This is a useful alternative to providing status update alerts via email for several reasons:
+ Slack has smart notification rules, which allows you to respond to urgent messages and get to non-critical issues when you have time
+ You can create a group/channel for each job or group the alerts into one group/channel, either way it's easy for you and others to organize your alerts
+ Slack is an extensible environment that means you can design custom integrations that trigger other actions based on the content of messages posted to a given room
+ You can send messages when frequent jobs complete successfully without worrying about clogging up your inbox
The source can be found …
=> Add: PDI SlackBot Plugin

marketplace.xml
This step allows you to merge streams with different schemas without first rearranging the fields, adding constants or modifying data meta types.
Let's say you want to take 2 text files and combine them into 1 text file. 
+ *Scenario:* The files have the exact same structure and field ordered
+ *Traditional Solution:* Simple transformation that reads in text files and sends rows directly to output
+ *Scenario:* The files share 6/10 fields and the other 4 fields are different in each file. The order of column names is not the same in the two files.
+ *Traditional Solution:* Use the Add Constants step to add missing fields, then use the Select Values step to rearrange the fields so they appear in the same order.
+ While the complex case is a little clunky, it isn't so bad with only 2 …
=> Add: PDI StreamSchemaMerge Plugin

marketplace.xml
This step allows you to de-duplicate concatenated lists.
When moving from normalized to denormalized data or dealing with attributes of an entity you may want a unique list of delimited values. For example, imagine you have a list of all the countries a person has visited, one entry for each city
```
England,Spain,Spain,Belgium,Belgium,Trinidad,Trinidad,Mexico,Trinidad
```
Now, imagine you want each entry in the list to be unique. You can pass the field to the Unique List step and get that result.
```
England,Spain,Belgium,Trinidad,Mexico
```
The source can be found [here](https://github.com/graphiq-data/pdi-uniquelist-plugin)
=> Add: PDI UniqueList Plugin

marketplace.xml
Downloading a template wasn’t working.
The endpoint is a simple resultfiles kind of etl that should zip those files out to the client.
Jut by replacing cpf-core-*, cpk-core-*, cpf-pentaho* and cpk-pentaho* did the trick, so I’ve created a new branch on the plugin called pentaho5. I’ll keep the old libs there and maintain master to pentaho6 builds.
=> Tapa new <version> for Pentaho 6.0

marketplace.xml
There were two <build_id> tags on the UniqueListStep entry.
I assumed the one without value should be removed as it's the default.
=> Fixed UniqueListStep double <build_id> tag

marketplace.xml
Update pivot4j plugin to work with Pentaho BI 6.0 (build #385).
=> Update pivot4j plugin for Pentaho BI 6.x

marketplace.xml
Hello there,
I'm Antonio Garcia-Dominguez, one of the presenters at PCM 2015. As suggested, I've broken off the permissions management part of ArtifactCatalog into its own plugin, and made it look a bit cleaner :-).
I have tried to test my marketplace.xml file using the recommended `~/.kettle/marketplaces.xml` file, but that seems to only work for PDI. Is there something like that for the BA Server?
Kind regards,
Antonio
=> Add entry for "ACL Dashboards"

marketplace.xml
Adding `v2.0.0` to the marketplace for initial use with PDI 6.0.
=> Additional Version: pdi-fastjsoninput-plugin, support for PDI 6.0

marketplace.xml
Sourceforge moved permanently urls on http to https.
=> AAAR links update (thank you sourceforge)

marketplace.xml
Hello,
I have released a new version of ArtifactCatalog with two bugfixes, and I'd like to make sure people get them. Could you please merge this when you can, if it's OK?
Kind regards,
Antonio
=> Add new version of ArtifactCatalog (1.0.1)

marketplace.xml
Porting on Pentaho 6.1.
Added flag ‘CLEAN_NODES_DELETED’ in ETL to avoid removed nodes extraction (default = false).
Improvements in terms of execution time (and stability) on huge repositories (tested in production environment with +2 Milion documents and +180.000 instances of workflows).
Separation of Alfresco extraction and data mart import in ETL.
Bugfix on Audit dashoboard not showing charts.
Various bugfixes.
=> AAAR v4.3 on Pentaho 6.1

marketplace.xml
This will remove pdi-fastjsoninput-plugin version 2.0 from the Marketplace. This version was for support for PDI 6 which is no longer necessary, as this code has been adopted to the main project.
Thanks again @pmalves 😄 🍻
=> Remove: pdi-fastjsoninput-plugin 2.0, support for PDI 6

marketplace.xml
This should stop an unsupported version of the IvyDD appearing in Pentaho 6.x
=> Fixed IvyDD Version details

marketplace.xml
FusionCharts XT installation Not Working
Update the marketplace download linksand version for the fusion charts plugin
=> Fix the issue #178

marketplace.xml
- Add installation instructions
- Add new 3.0 and 3.6 Versions
- Update download URLs from Sourceforge with direct mirrors
=> New BTable for Pentaho 5, 6 and 7

marketplace.xml
I just realized that Pentaho 5.x marketplace (probably is a Java7 problem) is not able to deal with  URLs starting with https for download. I'm actually using fixed links to Sourceforge mirror because it seems that HTTP Client PDI component used inside Pentaho Marketplace sometimes has problem with URL redirection. This is why I leaved direct mirror links starting with https for Pentaho version equals or greater than 6.0 while I used stardard http URLs for previous version (hoping they work fine in most cases). NOTE: I don't want to leave Sourceforge because I really love its analystics about downloads.
=> Updated URLs

marketplace.xml
This adds compatibility with PDI 5/6/7 and uses JTS 1.14.
=> Add version 1.2.1 of PDI GIS Plugins

marketplace.xml
Updated d3ComponentLibrary Marketplace entry to make it available for Pentaho 7.x versions.
=> d3ComponentLibrary - new plugin version for 7.x

marketplace.xml
The CKAN DataStore writer plugin allows users to upload tabular data to a CKAN data portal
=> Added CKAN DataStore plugin to Pentaho Marketplace

marketplace.xml
- Pentaho CDE widget - add parameters support - add iframe refresh.
- Added option to include 'All member' when place hierarchy.
- #170: Do not use cell ordinal as command parameter.
- #202: Fix error with drillthrough when changing the cube.
- Enabled export functionality in embedded report.
- Fixed issue #218 Correct support for non-numeric measure values.
- #216: Simplify embeded view by removing layouts.
- Fixed #220 Wrong table columns rendered with property column.
- #222 Optimze table rendering.
- Update Mondrian to 3.12.0.19-384.
=> Update Pivot4J to build #439

marketplace.xml
Renames some jars pertaining pentaho-reporting
=> [LPI] New version of language packs: 8.0-17.11.24

marketplace.xml
Added two additional plugins from the EMEA and APAC SE team. Also added a meta plugin linking all pre-sales generated plugins for easy bulk installation.
=> Pentaho se emea apac

marketplace.xml
New release of Pentaho MongoDB Delete Plugins
- This release to support MongoDB ver 3
=> Pentaho Mongo DB Delete Plugin : New release 2.0.0-RELEASE

marketplace.xml
Reference to install sparkl when using pentaho 8.2 or higher
=> Layout Editor Market Entry

marketplace.xml
Hi,
I updated the AWS SQS plugin and released a new Version (0.9.1) - please update Pentaho Marketplace.
Michael
=> Upgrade of AWS SQS Reader Plugin to version 0.9.1

marketplace.xml
package_url incorrectly pointed to SocrataOutput.zip and would error out when attempting to install, but should point to SocrataPlugin.zip. URL has been fixed.
=> fix package_url typo

marketplace.xml
- Updated to new version 0.9.2 of AWS-SQS-Reader (runs 7.1 to 9.0)
- Updated to new version 0.9.2 of AWS-SNS-Notify (runs 7.1 to 9.0)
=> - Updated AWS SQS Reader and AWS SNS Notify
