pentaho/marketplace-metadata

marketplace.xml
Hi @pamval,
Can you Review?
Cheers. :thumbsup: :stuck_out_tongue_closed_eyes:
=> Publishing the new Version of IvySE for Pentaho 5.2

marketplace.xml
Hi @pamval,
Can you review?
Cheers. :beer:
=> New IvyBC 1.0.2 version

marketplace.xml
Hi @pamval 
Can you check this it out. Its a simple plugin called Ivy User Details. Its a plugin that allows the user to save more details about themselves on the BIServer. The user logs in and they can save things like firstname, lastname, email to a Hibernate table that links to the username.
Cheers!
Harris
=> IvyUD Added

marketplace.xml
Hi @pamval,
Another one. :smile:  Can you review?
Cheers.
=> New IvyDD version for work with saiku 3.x

marketplace.xml
New release with bootstrap restyle for all the installation wizard and dashboards.
=> AAAR v2.4 release

marketplace.xml
New screenshots for the marketplace
=> AAAR screenshots

marketplace.xml
Hi all,
This is a new version of the marketplace.xml with simple redis input/output plugins added.
One quick question : I have another plugin which I would like to put on the market place. It is a plugin developped with sparkl though, is it the same process to post a sparkl plugin?
Regards,
Nicolas Haquet
=> new plugin : simple redis input/output

marketplace.xml
Necessary changes at marketplace.xml for the new version of Pentaho CE Audit. We are launching the 2.0 version of our Plugin.
Feel free to contact us to explain more about the new version of our plugin. This new version comes with some layout and bug fix and a new Dashboard to help more the Admin users of Pentaho.
=> Necessary changes at marketplace.xml for the new version of Pentaho CE Audit. We are launching the 2.0 version of our Plugin.

marketplace.xml
Hi @pamval ,
Can you review?
Basically, is new versions in almost all plugins (in special new template).
Cheers
=> Update Ivy plugins

marketplace.xml
AAAR v2.1 should be available for Pentaho 5.2.
=> AAAR v2.1 should be available for Pentaho 5.2

marketplace.xml
New plugin called Pentaho Performance Monitoring
=> New plugin called Pentaho Performance Monitoring

marketplace.xml
=> AAAR v2.4.1 release

marketplace.xml
Adding new plugin for Essbase to Pentaho marketplace : 
- Datasource connexion wizard
- Data output step
- Data input step
- MAXL Job entry
(https://github.com/bcolas/PDIEssbasePlugin/wiki)
=> Initialize Essbase Plugin

marketplace.xml
Some new features and bug fixes in the output step plugin, In parallel I moved the database part to an seperate database plugin.
=> - new version of ARSOutput step plugin and new database plugin

README.md, marketplace.xml, marketplace.xsd
- Changed schema so that all versions are required to have one branch and one version
- Added branch "Stable" to PDI market entries versions that did not have any branch
=> [MARKET-257] - Version element now requires Branch and Version

marketplace.xml
=> AAAR v3.0 release

marketplace.xml
@pamval or @pmalves please review
=> Added entry for CTE

marketplace.xml
Hi all, I deleted my old fork and created a new one so all of my old commits could be squashed into one.
So here is the right market_entry for the localizedmondrian plugin, which translate analysis reports.
Regards,
Nicolas Haquet
=> Added the localized mondrian plugin

marketplace.xml
=> - Updated marketplace version metadata for BA server 5.2

marketplace.xml
=> Reordering marketplace entries

marketplace.xml
Hi @mattcasters @mattyb149,
Can you review?
Cheers! :smile:
=> Publishing the Ivy MongoDB Steps

marketplace.xml
Updated support version to 5.2+, fixed some errors, allow variable for Number of Rows to Save
=> Updated Top/Bottom/First/Last PDI plugin

marketplace.xml
=> AAAR v3.1 release

marketplace.xml
=> PDI Jira 0.6 release

marketplace.xml
Updated components -- (descriptions to reflect this)
-bug fixes
-added demographic appends in personator component
-added golden record selection and surviroship in MatchUp
=> Updated Melissa Data components and functionality

marketplace.xml
Hi This is a Pentaho Kettle Step Plugin which aims at improving the data quality of the input data stream. I would like this plugin to be available in the Pentaho Marketplace. Please kindly have a look at the file and let me know incase of any concerns.
[Note: This is a fresh PR. I have requested a PR earlier, which due to my mistakes got messed up. Please close the prev. request id #343 and consider this as a new one.]
Thanks :)
=> Special Character Remover - PDI Plugin - Marketplace

marketplace.xml
=> startupRuleEngine: allowed installation on 5.4

marketplace.xml
Updated market entry fusion_plugin.
Added new version, updated old links.
=> Added FusionCharts Plugin v3.0.8

marketplace.xml
=> Corrected FusionCharts Plugin URLs

marketplace.xml
Hello @pamval 
Please review our request to upgrade support of BootstrapDashboardDesigner upto Pentaho 5.4
=> Upgrade support of BootstrapDashboardDesigner upto Pentaho 5.4

marketplace.xml
=> repositorySynchronizer: release 15.06.30

marketplace.xml
New plugin for Pentaho CE - Self Service BI
=> Self Service BI plugin

marketplace.xml
Add_3: PDI SequoiaDB Plugin(modify the package_url)
=> Add_3: PDI SequoiaDB Plugin(modify the package_url)

marketplace.xml
Hello @pamval,
Please review and update the description for our plugin, Self Service BI
=> Update description for Self Service BI plugin

marketplace.xml
Update description of Self Service BI plugin
=> Update description of Self Service BI plugin

marketplace.xml
Updated Support links and verbage to make it more clear to users of who supports our components as well as added links to our ticketing system for support (if email or phone are not desired)
=>    *Updated Support links and verbage to make it more clear to users

marketplace.xml
Limit to the Pentaho version compatibility of AAAR
=> Limit to the Pentaho version compatibility of AAAR

marketplace.xml
- Updated marketplace BA 5.X stable versions
=> - Added new marketplace BA/PDI osgi market entries

marketplace.xml
=> Add sequoiadb-screenshots

marketplace.xml
=> Add PDI 6.0 DB plugin for Apache Drill

marketplace.xml
=> Add PDI 6.0 DB plugin for Presto

marketplace.xml
New PDI plugin. It offers validation and extract additional information from NIP, REGON, PESEL (Polish tax numbers)
=>  Add: NIP, REGON, PESEL Validators (Polish tax numbers) 

marketplace.xml
Added Tapa [https://github.com/marpontes/tapa] <market_entry>
=> Added Tapa <market_entry>

marketplace.xml
This is the first commit of the pentaho waqe plugin.
=> waqe plugin

marketplace.xml
- Stream Schema Merge and SlackBot were pointing to old artifacts
=> Update package URLs to point to appropriate artifact

marketplace.xml
=> Disabled repositorySynchronizer in 6.x

marketplace.xml
Provides GIS steps for PDI : file input, file output, coordinates transformation, geoprocessing.
Installation from Marketplace with this configuration has been tested with a local set of marketplace.xml and marketplaces.xml in my .kettle folder.
Written by Atol Conseils & Développements
=> First version of PDI GIS Plugins

marketplace.xml
Hi Pentaho,
Tomorrow we will be launching DataCleaner 4.5 and this plugin update is meant to accomodate it as well.
With the release we offer also commercial support for the plugin. The plugin works with both community and commercial editions of DataCleaner. So in addition to a new plugin we've also updated the plugin metadata.
=> DataCleaner 4.5 plugin

marketplace.xml
=> Updated entries for sparkl plugins in 6.0

marketplace.xml
An entry has been added for the PentahoTransparentAuthentication plugin
=> added entry for the PentahoTransparentAuthentication plugin

marketplace.xml
@pamval or @pmalves please review
=> - Added entry for CLP

marketplace.xml
add credits to Ambiente Livre Team ( Paulo Pimentel, Rafaela Raganham and Marcio Junior Vieira) for 5.4 revision and translate
=> add credits

marketplace.xml
Adds 6.0 support to Token Replacement and Avro Output Plugins
=> Add new versions of Token Replacement and Avro Output Plugins

marketplace.xml
@pmalves @pamval Not sure if my Box account will stick around for long, so I moved my plugins to Dropbox
=> Move Matty B's plugins to Dropbox

marketplace.xml
@pmalves This is pointing at my Box account which will not be persisted, once the final landing spot for shims is determined, please update the URL for the ZIP package.  Cheers!
=> Add Hadoop 0.20 shim (for PDI 6.0) to Marketplace

marketplace.xml
@pamval 
@pmalves 
please review
=> - Updated and corrected entries for PDI plugins

marketplace.xml
=> - Added missing 'development stage' to several PDI plugins

marketplace.xml
Hi @pamval : This pull request to update metadata of MongoDB Delete Plugin ver. 1.0.1-RELEASE
=> New Release : version 1.0.1-RELEASE

marketplace.xml
@pamval Please check if this looks OK and help merge.  Thanks!
=> Add Weka Analyzer Viz plugin for 6.1 BA Server

marketplace.xml
=> Increment Version: Fast JSON Input

marketplace.xml
Fixed https://github.com/RuckusWirelessIL/pentaho-kafka-producer/issues/7
=> Upgraded Kafka Producer

marketplace.xml
Added a new version of the FusionCharts Plugin.
=> New version of FusionCharts Plugin

marketplace.xml
Updated version of the FusionCharts Plugin.
=> Updated version of Fusion Plugin

marketplace.xml
Updated fusion plugin version for Pentaho 6.
=> Updated Fusion Plugin 

marketplace.xml
@pamval This releases addresses the issue http://redmine.webdetails.org/issues/3499
=> [languagePacks] Release 16.04.02

marketplace.xml
DataCleaner plugin has been updated  to work with Kettle 6.0.x. Moreover,  the description for old plugin version has been changed.
=> Updated DataCleaner plugin for Kettle 6.0.x 

marketplace.xml
Hello there,
I've finally completed version 1.0.0 of ArtifactCatalog [1], and I'd like to have it considered for inclusion in the Pentaho Marketplace.
[1]: https://github.com/bluezio/pentaho-artifactCatalog
Thanks!
Antonio
=> Add metadata for Artifact Catalog

marketplace.xml
And removed the AAAR v4.1 version.
=> AAAR v4.2 new release

marketplace.xml
Changed link to github to (temporary) solve the sorurceforge issue.
=> AAAR links update (sourceforge links issue)

marketplace.xml
And cleaning of the old versions.
=> AAAR links to github repo

marketplace.xml
CMIS Input plugin link to github
=> CMIS Input plugin link to github

marketplace.xml
Hello; can you please review this addition to the marketplace.
=> added PDI marketplace entry for pdi-xero step plugin

marketplace.xml
update the license field on the marketplace metadata file
=> Xero plugin; update the license field on the marketplace metadata file

marketplace.xml
=> Switched to Sourceforge download again

marketplace.xml
Fixes a bug where field values were repeated if previous value was not null and current value is.
https://github.com/graphiq-data/pdi-fastjsoninput-plugin/pull/8
=> Update fastjsoninput to 1.0.5

marketplace.xml
As discussed with Pedro Alves, here is our plugin for Cassandra that uses the Datastax driver.
=> Add entry for incentro-cassandra-plugin

marketplace.xml
Hello, @pamval 
Please review and merge request to add new plugin for the PDI.
Thanks
=> New PDI plugin - Inter Repository Object Transfer

marketplace.xml
Hi @pamval 
Now is tested.
Cheers
=> Ivy stack updated

marketplace.xml
=> CST: Release 16.04.06

marketplace.xml
@pamval Please review. The zip files are already uploaded to the ctools.pentaho.com website.
=> [LPI] Release 16.05.04

marketplace.xml
Self Service BI plugin - pentaho support version upgrade 
Upgrade support upto Pentaho 6.1
=> Self Service BI plugin - pentaho support version upgrade

marketplace.xml
* Update to PrimeFaces 5.3.
* Fix UI glitch with d&d in the navigator view.
* Fix an error with drillthrough MDX generation(#200).
=> Update Pivot4J to build #394

marketplace.xml
Updated DataCleaner plugin to version 4.5.3
=> Updated DataCleaner plugin to version 4.5.3

marketplace.xml
updated DataCleaner plugin to avoid the issue: http://jira.pentaho.com/browse/PDI-15371
=> updated DataCleaner plugin

marketplace.xml
* Fix the classloader problem on saving reports.
* Fix the drillthrough dialog selection problem.
* Fix a potential NPE regarding request.getPathInfo() API.
=> Update Pivot4J to build #397

marketplace.xml
- Stream Schema Merge
- increment version
- move to phase 3
- Unique List
- move to phase 3
- SlackBot
- move to phase 3
=> Update version info for 3 Graphiq plugins

marketplace.xml
Added MelissaData components and updated descriptions of current components to reflect recent improvements.
=> Added new components and descriptions

marketplace.xml
Changed Links for Melissa Data components
=> Changed links

marketplace.xml
Self Service BI - Bi Server plugin - New Version - v 1.2.0
=> Self Service BI - Bi Server plugin - New Version - v 1.2.0

marketplace.xml
- Added support for PDI 7
- Fixed issue with null fields
=> Updated Kafka consumer and producer plug-ins to the latest version

marketplace.xml
Added the new tested Melissa Data General Cleansing Component to the marketplace
=> Added MDCleanser to marketplace

marketplace.xml
Fixed some spelling errors as well as changed "Data Enrichment" to "Data Quality"
=> Fixed some spelling errors

marketplace.xml
Self Service BI - new version with bug fixes
=> Self Service BI - new version with bug fixes

marketplace.xml
This is an update of Essbase PDI plugin for PDI 5
=> New version of plugin for PDI 5

marketplace.xml
New version of essbase plugin for PDI 6.x
=> Update Essbase Plugin for PDI 6.x

marketplace.xml
=> Update Salesforce Bulk Input for PDI 6.x

README.md, marketplace.xml, marketplace.xsd
=> Add maximum of 3 screenshots per plugin.

marketplace.xml
updated DC version and kettle-core dependency
=> Updated DataCleaner plugin 

marketplace.xml
AAAR download link does not work.
=> AAAR download link does not work.

marketplace.xml
Updated the maximum Parent version of the fusion plugin
=> update max pentaho version supported

marketplace.xml
problem with download with JDK
=> Changed description with notes about Pre-Installation instructions and

marketplace.xml
=> Update marketplace.xml with new Sourceforge links

marketplace.xml
@pamval @pmalves please review
=> Added new Community Startup Tabs version, corresponding to 7.x.

marketplace.xml
Adds variable-based filename fixes
=> MaxMind GeoIP Plugin Update

marketplace.xml
=> updated DC the plugin version

marketplace.xml
Broken link from sourceforge for AAAR
=> Broken link from sourceforge for AAAR

marketplace.xml
Hi,
I have created a plugin to use splunk as input in a kettle transformation. I would like to see it listed in the marketplace :-)
Cheers,
Sascha
=> add splunk plugin

marketplace.xml
See http://jira.pentaho.com/browse/PDI-16129 for background info.
=> Add PDI Odoo Plugin

marketplace.xml
@pamval: Please have a look again. Thank you!
Added PDI plugin entries (IMS Reader, Websphere MQ Reader, Websphere MQ Writer) for the marketplace.
=> New plugins

marketplace.xml
Hi.
I've Just updated WAQE for Pentaho 7.X version.
Can you please update the marketplace?
Thanks
=> Updated New version of WAQE

marketplace.xml
Alflytics release for 7.1 and bye bye AAAR.
=> Alflytics release for 7.1

marketplace.xml
Image changes to Alflytics release.
=> Image changes to Alflytics release.

marketplace.xml
* Upgraded Kafka consumer plug-in to version 1.7
* Upgraded Kafka producer plug-in to version 1.9
Major change: moving to annotation-based plug-in registration method
=> Released new versions of Kafka integration plug-ins

marketplace.xml
Dear sir or madam,
please review the following changes to all 3 Proventa PDI plugins:
1. IMS Reader:
- New download link.
- Description extended by adding reference to documentation.
2. MQ Writer
- Typo correction "MQ writer" in header.
- New download link.
- Description extended by adding reference to documentation.
3. MQ Reader
- New download link.
- Description extended by adding reference to documentation.
Best regards,
Dirk Aumueller
=> Revision of Proventa plugin XML entries

marketplace.xml
=> Fixing sparkl versions

marketplace.xml
Adding first release for CTools SVG Component.
=> SVG Component release

marketplace.xml
This is the upgrade for Pentaho 7.1
=> FusionChartPlugin v5.0.0

marketplace.xml
We have developed this plugin to community usage. Willing to see it available on marketplace next weeks.
=> Including STPivot4 in pentaho marketplace

marketplace.xml
Added marketplace entry for new CloseIT SAS Reader PDI plugin.
=> Commiting marketplace entry for CloseIT SAS reader.

marketplace.xml
SelfServiceBI - Plugin - Community Version 2.0.0 Release
For Pentaho 6 and 7
=> SelfServiceBI - Plugin - Community Version 2.0.0 Release

marketplace.xml
Hello team,
This is the Git plugin I presented at PCM17.
@jbleuel labeled this as "community lane project classification 3 - stable product".
Please review and merge my request.
Thanks,
Hiromu Hota
=> Add SpoonGit (pdi-git-plugin)

marketplace.xml
SelfServiceBI : BA plugin : Issues fixes, Pentaho 8 support
=> SelfServiceBI : BA plugin : Issues fixes, Pentaho 8 support

marketplace.xml
PDI plugin : Plugin added : Get Carte ID
=> PDI plugin : Plugin added : Get Carte ID 

marketplace.xml
Updated all component pages to reflect company rebranding.
New icons, new text, updated web links and phone numbers.
=> Updated component pages to reflect company rebranding

marketplace.xml
=> Changed "Melissa Global Intelligence" to "Melissa"

marketplace.xml
Added a new entry for the new AWS-SNS-Plugin.
=> Added Entry for PDI Step AWS-SNS-Notify

marketplace.xml
=> Added some extra blurbs for each component

marketplace.xml
Additional to the new versions, I'm now informing that two restarts are needed after install.
=> Added a new Tapa release compatible with 7.1 and 8.0.

marketplace.xml
Hi @pamval,
Please merge the changes into master
Thanks
=> SelfServiceBI - New version 2.0.2 release - New charts and bug fixes

marketplace.xml
=> New version for WAQE

marketplace.xml
My first marketplace entry - please check
=> Added rebuild of stream schema merge for PDI 8.0

marketplace.xml
Made a typo in the author line (copy paste error). Fixed now. Please allow update.
=> Corrected author tag line

marketplace.xml
I've updated SpoonGit. Please merge this patch.
=> Updated SpoonGit (pdi-git-plugin) for 1.0.1

marketplace.xml
SelfServiceBI version 2.1.2 release
=> SelfServiceBI version 2.1.2 release

marketplace.xml
PDI Google Plugin Steps: version 0.0.1
=> Include pdi-google-plugin to marketplace

marketplace.xml
Update URLs to HTTPS where sites support HTTPS connections
=> Update Screenshots and Packages to HTTPS

marketplace.xml
Hi,
This plugin provide Pentaho DI job entrie for executing a AS/400 CL Commands.
Nicolas
=> Add PDI plugin for executing AS/400 command

marketplace.xml
Hi,
I upgraded the Version of my AWS SNS Notify plugin with some new features and added the AWS SQS Reader Plugin for Pentaho DI. Please pull.
Michael
=> Version Upgrade of AWS SNS Plugin and new Plugin AWS SQS Reader

marketplace.xml
Fix error saving step meta to repository
=> New version 1.0.1 Coalesce plugin

marketplace.xml
This plugin provides an output step in a transformation to publish data to a Socrata dataset.
=> Add PDI Plugin for Socrata

marketplace.xml
Added new entry in the Marketplace. Market entry is related to Layout Editor, a sparkl plugin to build CTools dashboards.
@pamval please review
=> Layout Editor Market Entry

marketplace.xml
Update Plugin ID which was miswritten.
@pamval please review
=> Updated ID for Layout Editor which was misswritten.

marketplace.xml
@pamval please review.
created 2 versions entries in the marketplace. One for Pentaho 8.1 and above, and another only for 8.0
=> layout Editor Versions 

marketplace.xml
1. Added ARS Input Plugin
2. Changed ARS Output Plugin
- Other package_url 
- Added min Version
3. Changed ARS Database Plugin
- Other package_url 
- Added additional version 0.7.2 for 8.2 due API change of DatabaseFactoryInterface 
- Changed version 0.7.0, added min/max_parent_version 5.0/8.1
=> Added ARS Input Plugin, Changed URL for ARS DB/Output Plugin

marketplace.xml
New 3.0.1 version supports GeoIP2 database format
=> Update MaxMind GeoIP Plugin

.gitignore, marketplace.xml
@pentaho/millenniumfalcon please review.
=> [BACKLOG-32582] Add jpivot to marketplace

marketplace.xml
@pentaho/millenniumfalcon please review
When the final build for 9.0.0.1 is complete, we will update the link of the build to that version.
=> [BACKLOG-32582] JPivot build with the fix that enable users to uninstall the plugin.

marketplace.xml
Hi, I add new plugin for the community.
Thanks.
=> Add new plugin step Generate Charts

marketplace.xml
This is a new plugin I would like to be added to the marketplace...
Not sure this is the good procedure but let's see.
jfmonteil@gmail.com
=> Update marketplace.xml for new PDI Step plugin PentahoGoogleSheetsPlugin

marketplace.xml
=> Information

marketplace.xml
=> Updated SpoonGit (pdi-git-plugin) for 1.1.1

marketplace.xml
Publish datafor visualizer plugin
=> 申请发布datafor visualizer插件

marketplace.xml
I made a step that allows to send messages from PDI to a rocketchat server. Would be cool if you guys could review the marketplace entry for it 😃
=> Rocketchat-step entry

marketplace.xml
Bug fix for variable replacement
=> Update for ReadExcelHeader plugin

marketplace.xml
Sorry seems like i somehow messed up my git history this time.
But the last commit is also for my plugin, so it shouldn't mess anything up.
=> New Version for ReadExcelHeader

marketplace.xml
Modify the version.branch attribute in the marketplace.xml to be consistent with plugin version.xml, so users of the old version will be notified on the marketplace to update and upgrade
=> Update marketplace.xml for visualizer versioin3.3

marketplace.xml
Brazilian guys said it worked on 9.1...
=> Bumped up saiku version

marketplace.xml
Add new step to pdi, get the public IP on running server
=> Add Entry  Get Public IP

marketplace.xml
Visualizer-6.03 version upgrade
=> maketplace.xml  upgrade
